trigger:
  - main

variables:
  - name: resourceGroupName
    value: 'rg-vnet-example'
  - name: location
    value: 'eastus'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Current directory: $(pwd)"
      echo "List of files in current directory:"
      ls -R

- task: AzureCLI@2
  inputs:
    azureSubscription: 'terraform-demo'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Create resource group if it doesn't exist
      az group create --name $(resourceGroupName) --location $(location)

      # Deploy the Bicep template
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file $(Build.SourcesDirectory)/main.bicep \
        --parameters \
          name=myVNet \
          addressPrefixes="['10.0.0.0/16']" \
          subnets="[{'name': 'default', 'addressPrefix': '10.0.0.0/24'}]"